steps:
  # Step 1: Build backend Docker image
  - name: "gcr.io/cloud-builders/docker"
    id: "build-backend"
    args:
      - "build"
      - "-f"
      - "backend/Dockerfile"
      - "-t"
      - "${_REGISTRY}/backend:$SHORT_SHA"
      - "-t"
      - "${_REGISTRY}/backend:latest"
      - "."

  # Step 2: Build frontend Docker image
  - name: "gcr.io/cloud-builders/docker"
    id: "build-frontend"
    args:
      - "build"
      - "-f"
      - "frontend/Dockerfile"
      - "--build-arg"
      - "VITE_API_URL=${_API_URL}"
      - "--build-arg"
      - "VITE_WS_URL=${_WS_URL}"
      - "-t"
      - "${_REGISTRY}/frontend:$SHORT_SHA"
      - "-t"
      - "${_REGISTRY}/frontend:latest"
      - "."

  # Step 3: Build marketing Docker image
  - name: "gcr.io/cloud-builders/docker"
    id: "build-marketing"
    args:
      - "build"
      - "-f"
      - "marketing/Dockerfile"
      - "-t"
      - "${_REGISTRY}/marketing:$SHORT_SHA"
      - "-t"
      - "${_REGISTRY}/marketing:latest"
      - "."

  # Step 4: Push backend image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    id: "push-backend"
    args:
      - "push"
      - "--all-tags"
      - "${_REGISTRY}/backend"
    waitFor:
      - "build-backend"

  # Step 5: Push frontend image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    id: "push-frontend"
    args:
      - "push"
      - "--all-tags"
      - "${_REGISTRY}/frontend"
    waitFor:
      - "build-frontend"

  # Step 6: Push marketing image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    id: "push-marketing"
    args:
      - "push"
      - "--all-tags"
      - "${_REGISTRY}/marketing"
    waitFor:
      - "build-marketing"

  # Step 7: Update Kubernetes deployment image tags
  - name: "gcr.io/cloud-builders/kubectl"
    id: "update-k8s-images"
    args:
      - "set"
      - "image"
      - "deployment/api-server"
      - "api-server=${_REGISTRY}/backend:$SHORT_SHA"
      - "-n"
      - "flowmaestro"
    env:
      - "CLOUDSDK_COMPUTE_REGION=${_GKE_REGION}"
      - "CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}"
    waitFor:
      - "push-backend"

  # Step 8: Update Temporal worker deployment
  - name: "gcr.io/cloud-builders/kubectl"
    id: "update-worker-image"
    args:
      - "set"
      - "image"
      - "deployment/temporal-worker"
      - "temporal-worker=${_REGISTRY}/backend:$SHORT_SHA"
      - "-n"
      - "flowmaestro"
    env:
      - "CLOUDSDK_COMPUTE_REGION=${_GKE_REGION}"
      - "CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}"
    waitFor:
      - "push-backend"

  # Step 9: Wait for API server rollout
  - name: "gcr.io/cloud-builders/kubectl"
    id: "wait-api-rollout"
    args:
      - "rollout"
      - "status"
      - "deployment/api-server"
      - "-n"
      - "flowmaestro"
      - "--timeout=5m"
    env:
      - "CLOUDSDK_COMPUTE_REGION=${_GKE_REGION}"
      - "CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}"
    waitFor:
      - "update-k8s-images"

  # Step 10: Wait for worker rollout
  - name: "gcr.io/cloud-builders/kubectl"
    id: "wait-worker-rollout"
    args:
      - "rollout"
      - "status"
      - "deployment/temporal-worker"
      - "-n"
      - "flowmaestro"
      - "--timeout=5m"
    env:
      - "CLOUDSDK_COMPUTE_REGION=${_GKE_REGION}"
      - "CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}"
    waitFor:
      - "update-worker-image"

  # Step 11: Upload frontend static files to Cloud Storage
  - name: "gcr.io/cloud-builders/docker"
    id: "extract-frontend"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        docker create --name frontend-container ${_REGISTRY}/frontend:$SHORT_SHA
        docker cp frontend-container:/usr/share/nginx/html ./frontend-dist
        docker rm frontend-container
    waitFor:
      - "push-frontend"

  # Step 12: Sync frontend to Cloud Storage
  - name: "gcr.io/cloud-builders/gsutil"
    id: "upload-frontend"
    args:
      - "-m"
      - "rsync"
      - "-r"
      - "-c"
      - "-d"
      - "./frontend-dist"
      - "gs://${_FRONTEND_BUCKET}"
    waitFor:
      - "extract-frontend"

  # Step 13: Set cache control headers
  - name: "gcr.io/cloud-builders/gsutil"
    id: "set-cache-headers"
    args:
      - "-m"
      - "setmeta"
      - "-h"
      - "Cache-Control:public, max-age=31536000"
      - "-r"
      - "gs://${_FRONTEND_BUCKET}/assets/**"
    waitFor:
      - "upload-frontend"

  # Step 14: Extract and upload marketing site
  - name: "gcr.io/cloud-builders/docker"
    id: "extract-marketing"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        docker create --name marketing-container ${_REGISTRY}/marketing:$SHORT_SHA
        docker cp marketing-container:/usr/share/nginx/html ./marketing-dist
        docker rm marketing-container
    waitFor:
      - "push-marketing"

  # Step 15: Sync marketing to Cloud Storage
  - name: "gcr.io/cloud-builders/gsutil"
    id: "upload-marketing"
    args:
      - "-m"
      - "rsync"
      - "-r"
      - "-c"
      - "-d"
      - "./marketing-dist"
      - "gs://${_MARKETING_BUCKET}"
    waitFor:
      - "extract-marketing"

# Substitution variables
substitutions:
  _REGISTRY: "us-central1-docker.pkg.dev/${PROJECT_ID}/flowmaestro"
  _GKE_CLUSTER: "flowmaestro-cluster"
  _GKE_REGION: "us-central1"
  _API_URL: "https://api.yourdomain.com"
  _WS_URL: "wss://api.yourdomain.com"
  _FRONTEND_BUCKET: "flowmaestro-frontend-${PROJECT_ID}"
  _MARKETING_BUCKET: "flowmaestro-marketing-${PROJECT_ID}"

# Build options
options:
  machineType: "E2_HIGHCPU_8"
  logging: CLOUD_LOGGING_ONLY
  dynamicSubstitutions: true

# Timeout for entire build
timeout: "1800s"

# Images to be pushed (tracked by Cloud Build)
images:
  - "${_REGISTRY}/backend:$SHORT_SHA"
  - "${_REGISTRY}/backend:latest"
  - "${_REGISTRY}/frontend:$SHORT_SHA"
  - "${_REGISTRY}/frontend:latest"
  - "${_REGISTRY}/marketing:$SHORT_SHA"
  - "${_REGISTRY}/marketing:latest"
