version: "3.8"

services:
    # PostgreSQL Database
    postgres:
        image: postgres:15-alpine
        container_name: flowmaestro-postgres
        environment:
            POSTGRES_DB: flowmaestro
            POSTGRES_USER: flowmaestro
            POSTGRES_PASSWORD: flowmaestro_dev_password
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U flowmaestro"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - flowmaestro

    # Redis Cache
    redis:
        image: redis:7-alpine
        container_name: flowmaestro-redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - flowmaestro

    # Temporal Server
    temporal:
        image: temporalio/auto-setup:1.23.0
        container_name: flowmaestro-temporal
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            - DB=postgresql
            - DB_PORT=5432
            - POSTGRES_USER=flowmaestro
            - POSTGRES_PWD=flowmaestro_dev_password
            - POSTGRES_SEEDS=postgres
            - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
        ports:
            - "7233:7233"
        volumes:
            - ./docker/temporal/dynamicconfig:/etc/temporal/config/dynamicconfig
        networks:
            - flowmaestro

    # Temporal Web UI
    temporal-ui:
        image: temporalio/ui:2.22.3
        container_name: flowmaestro-temporal-ui
        depends_on:
            - temporal
        environment:
            - TEMPORAL_ADDRESS=temporal:7233
            - TEMPORAL_CORS_ORIGINS=http://localhost:3000
        ports:
            - "8088:8080"
        networks:
            - flowmaestro

    # Temporal Admin Tools (optional, for CLI access)
    temporal-admin-tools:
        image: temporalio/admin-tools:1.23.0
        container_name: flowmaestro-temporal-admin
        depends_on:
            - temporal
        environment:
            - TEMPORAL_ADDRESS=temporal:7233
        stdin_open: true
        tty: true
        networks:
            - flowmaestro

    # Adminer - Lightweight PostgreSQL Admin Tool
    adminer:
        image: adminer:latest
        container_name: flowmaestro-adminer
        depends_on:
            postgres:
                condition: service_healthy
        ports:
            - "8080:8080"
        environment:
            ADMINER_DEFAULT_SERVER: postgres
        networks:
            - flowmaestro

networks:
    flowmaestro:
        driver: bridge

volumes:
    postgres_data:
    redis_data:
