-- Add AI metadata fields to workflows table
ALTER TABLE flowmaestro.workflows
ADD COLUMN ai_generated BOOLEAN DEFAULT FALSE,
ADD COLUMN ai_prompt TEXT;

-- Add comment to document the columns
COMMENT ON COLUMN flowmaestro.workflows.ai_generated IS 'Whether this workflow was generated by AI';
COMMENT ON COLUMN flowmaestro.workflows.ai_prompt IS 'The original prompt used to generate the workflow (if AI-generated)';
