# Temporal Dynamic Configuration for Development

# System settings
system.forceSearchAttributesCacheRefreshOnRead:
  - value: true
    constraints: {}

# Frontend settings
frontend.enableUpdateWorkflowExecution:
  - value: true
    constraints: {}

# History settings
history.maxAutoResetPoints:
  - value: 20
    constraints: {}

# Matching settings
matching.numTaskqueueReadPartitions:
  - value: 5
    constraints: {}

matching.numTaskqueueWritePartitions:
  - value: 5
    constraints: {}

# Worker settings
worker.recentActivityCount:
  - value: 10
    constraints: {}

# Visibility settings
system.enableReadFromSecondaryAdvancedVisibility:
  - value: true
    constraints: {}
